import { Webinar } from '@/types/webinar'

export const mockWebinars: Webinar[] = [
  {
    id: '1',
    title: 'Введение в React Hooks',
    description: 'Базовый вебинар о современных подходах к разработке на React с использованием хуков',
    scheduledAt: '2024-11-25T14:00:00Z',
    status: 'scheduled',
    active: true,
    createdAt: '2024-11-20T10:00:00Z',
    updatedAt: '2024-11-20T10:00:00Z',
    maxParticipants: 50,
    currentParticipants: 23,
    roomSettings: {
      allowRecording: true,
      allowChat: true,
      allowScreenShare: false,
      requirePassword: false,
    },
    tags: ['React', 'Frontend', 'JavaScript'],
  },
  {
    id: '2',
    title: 'Продвинутая работа с TypeScript',
    description: 'Изучим продвинутые возможности TypeScript: дженерики, декораторы, утилиты',
    scheduledAt: '2024-11-23T16:00:00Z',
    startedAt: '2024-11-23T16:00:00Z',
    status: 'active',
    active: true,
    createdAt: '2024-11-19T09:00:00Z',
    updatedAt: '2024-11-23T16:00:00Z',
    maxParticipants: 30,
    currentParticipants: 18,
    roomSettings: {
      allowRecording: true,
      allowChat: true,
      allowScreenShare: true,
      requirePassword: true,
      password: 'ts2024',
    },
    tags: ['TypeScript', 'Frontend', 'Advanced'],
  },
  {
    id: '3',
    title: 'Node.js микросервисы',
    description: 'Практический вебинар по созданию микросервисной архитектуры на Node.js',
    scheduledAt: '2024-11-28T18:00:00Z',
    status: 'scheduled',
    active: true,
    createdAt: '2024-11-18T11:00:00Z',
    updatedAt: '2024-11-18T11:00:00Z',
    maxParticipants: 100,
    currentParticipants: 45,
    roomSettings: {
      allowRecording: false,
      allowChat: true,
      allowScreenShare: true,
      requirePassword: false,
    },
    tags: ['Node.js', 'Backend', 'Architecture'],
  },
  {
    id: '4',
    title: 'Вебинар по CSS Grid и Flexbox',
    description: 'Современные способы верстки сложных интерфейсов с помощью CSS Grid и Flexbox',
    status: 'draft',
    active: false,
    createdAt: '2024-11-17T14:00:00Z',
    updatedAt: '2024-11-22T10:00:00Z',
    roomSettings: {
      allowRecording: true,
      allowChat: true,
      allowScreenShare: true,
      requirePassword: false,
    },
    tags: ['CSS', 'Frontend', 'Layout'],
  },
  {
    id: '5',
    title: 'MongoDB для начинающих',
    description: 'Основы работы с NoSQL базой данных MongoDB: от установки до продвинутых запросов',
    scheduledAt: '2024-11-22T15:00:00Z',
    startedAt: '2024-11-22T15:00:00Z',
    endedAt: '2024-11-22T16:30:00Z',
    status: 'ended',
    active: false,
    createdAt: '2024-11-16T12:00:00Z',
    updatedAt: '2024-11-22T16:30:00Z',
    maxParticipants: 75,
    currentParticipants: 52,
    duration: 90,
    roomSettings: {
      allowRecording: true,
      allowChat: true,
      allowScreenShare: false,
      requirePassword: false,
    },
    tags: ['MongoDB', 'Database', 'NoSQL'],
  },
]

export function getMockStats() {
  const stats = {
    total: mockWebinars.length,
    active: mockWebinars.filter(w => w.status === 'active').length,
    scheduled: mockWebinars.filter(w => w.status === 'scheduled').length,
    drafts: mockWebinars.filter(w => w.status === 'draft').length,
  }
  return stats
}